services:
  web:
    container_name: php
    build:
      context: app_php
      target: builder
    ports:
      - '8080:80'
      - '8081:81'
    volumes:
      # Monte le code source
      - ./data:/var/www/html
      # Monte les configurations Apache
      - ./app_php/data/ci.conf:/etc/apache2/sites-available/ci.conf
      - ./app_php/data/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./app_php/data/ports.conf:/etc/apache2/ports.conf
    # Commande pour activer le site au d√©marrage si non fait dans le Dockerfile
    command: bash -c "a2ensite ci.conf && apache2-foreground"

  mysql:
    container_name: mysql8
    image: docker.io/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
  phpmyadmin:
      image: docker.io/phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mysql
        PMA_USER: user
        PMA_PASSWORD: pass
        UPLOAD_LIMIT: 20M
      ports:
        - 8082:80

  
  

